name: Ruby

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'fix-*'

  pull_request:

permissions:
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: RuboCop
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.2'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.test_file }} (Ruby ${{ matrix.ruby }})
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '4.0.2'
        test_file:
          - test_client
          - test_player

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specific test
        run: bundle exec ruby -Ilib -Itest test/${{ matrix.test_file }}.rb
